SECRET_KEY = "SOVERYSECRET!"
SQLALCHEMY_DATABASE_URI = "postgresql://superset_user:superset_pass@postgres:5432/superset_metadata"
SQL_MAX_ROW = 1000000
ROW_LIMIT = 1000000
VIZ_ROW_LIMIT = 1000000
SAMPLES_ROW_LIMIT = 1000000
FILTER_SELECT_ROW_LIMIT = 1000000
QUERY_SEARCH_LIMIT = 1000000
DISPLAY_MAX_ROW = 1000000
DEFAULT_SQLLAB_LIMIT = 1000000
FEATURE_FLAGS = {
    "ALERT_REPORTS": True,
    "DATAPANEL_CLOSED_BY_DEFAULT": True,
    "DASHBOARD_VIRTUALIZATION": True,
    "DASHBOARD_RBAC": True,
    "ENABLE_TEMPLATE_PROCESSING": True,
    "ESCAPE_MARKDOWN_HTML": True,
    "LISTVIEWS_DEFAULT_CARD_VIEW": True,
    "THUMBNAILS": True,
    "DRILL_BY": True,
    "DRILL_TO_DETAIL": True,
    "HORIZONTAL_FILTER_BAR": True,
    "ESTIMATE_QUERY_COST": True,
    "TAGGING_SYSTEM": True,
    "HTML_SANITIZATION": False,
}